// Auto-generated from filee.txt — do not edit manually; re-run scripts/generate-privacy-copy.mjs
export const PRIVACY_TITLE = "MaritimeLink Privacy Policy";

export const PRIVACY_META = [
    "Company Registration Number: 16976752",
    "Approved By: MaritimeLink Management",
    "Effective Date: 02 July 2026",
    "Review Frequency: Annually or upon any material change to applicable legislation, platform functionality or processing activities.",
    "Registered Address: Flat 2, 290 Beverly Road, Hull, UK.  HU5 1AX",
    "Version: 1.0"
];

export const PRIVACY_SECTIONS = [
    {
        "number": "1",
        "title": "INTRODUCTION",
        "content": "Welcome to MaritimeLink.\nMaritimeLink Ltd (\"MaritimeLink\", \"we\", \"our\", or \"us\") is committed to protecting and respecting your privacy. We recognise that users entrust us with highly sensitive professional and personal information, including identity verification documents, professional qualifications, employment history, training records, and maritime certification data. Protecting this information is fundamental to maintaining trust in the MaritimeLink platform.\nThis Privacy Policy explains how MaritimeLink collects, uses, stores, shares and protects your personal information whenever you access or use:\nthe MaritimeLink website; \nthe MaritimeLink mobile applications; \nthe Professional Dashboard; \nthe Recruiter Portal; \nthe Training Provider Portal; \nthe Admin Platform; \nthe MaritimeLink Document Wallet; \nthe MaritimeLink CV Builder; \nour messaging system; \nour verification services; \nany other services operated by MaritimeLink. \nThis Privacy Policy has been prepared in accordance with:\nUK General Data Protection Regulation (\"UK GDPR\"); \nData Protection Act 2018; \nPrivacy and Electronic Communications Regulations 2003 (\"PECR\"); \napplicable UK privacy legislation. \nWhere applicable, MaritimeLink also aligns its practices with the EU General Data Protection Regulation (EU GDPR) when processing data relating to individuals located within the European Economic Area.\nBy using MaritimeLink, you acknowledge that you have read and understood this Privacy Policy."
    },
    {
        "number": "2",
        "title": "WHO WE ARE",
        "content": "MaritimeLink Ltd is the data controller responsible for your personal data.\nData Controller\nMaritimeLink Ltd\nUnited Kingdom\nEmail:\nprivacy@maritimelink.co\nWebsite:\nwww.maritimelink.co\nWhere required under applicable law, MaritimeLink has appointed a Data Protection Lead responsible for overseeing compliance with UK data protection legislation.\nQuestions regarding this Privacy Policy may be directed to:\nprivacy@maritimelink.co"
    },
    {
        "number": "3",
        "title": "OUR COMMITMENT TO YOUR PRIVACY",
        "content": "MaritimeLink has been specifically designed for the maritime industry.\nUnlike general recruitment websites, MaritimeLink stores professional compliance documentation, maritime qualifications and identity verification records that require enhanced levels of security and confidentiality.\nWe therefore operate privacy by design and privacy by default throughout our platform.\nEvery major feature of MaritimeLink has been developed with data protection as a core principle, including:\nVerified Professional Badge \nKYC Verification \nOCR-assisted document validation \nSecure Digital Document Wallet \nSecure Document Sharing \nMaritime CV Builder \nRecruiter Portal \nTraining Marketplace \nMessaging System \nSubscription Services \nIdentity Verification \nCompliance Monitoring \nAccount Security \nOnly information that is necessary to provide these services is collected."
    },
    {
        "number": "4",
        "title": "DEFINITIONS",
        "content": "For the purposes of this Privacy Policy:\nAccount\nmeans your MaritimeLink user account.\nAdmin\nmeans authorised MaritimeLink staff responsible for platform administration, moderation, verification and support.\nAI Processing\nmeans automated software used to assist document validation, fraud detection, text extraction or quality assurance.\nCV Builder\nmeans MaritimeLink's structured maritime curriculum vitae generation system.\nData Controller\nhas the meaning defined under Article 4 UK GDPR.\nDocument Wallet\nmeans MaritimeLink's encrypted digital certificate storage facility.\nKYC\nmeans Know Your Customer identity verification.\nOCR\nmeans Optical Character Recognition technology used to read information from uploaded documents.\nPersonal Data\nmeans any information relating to an identified or identifiable natural person.\nProcessing\nhas the meaning provided under Article 4 UK GDPR.\nProfessional\nmeans a registered seafarer using MaritimeLink.\nRecruiter\nmeans a recruitment organisation registered on MaritimeLink.\nTraining Provider\nmeans a maritime training organisation registered on MaritimeLink.\nVerified Professional Badge\nmeans MaritimeLink's verification status awarded after successful completion of identity verification and document validation procedures."
    },
    {
        "number": "5",
        "title": "SCOPE OF THIS PRIVACY POLICY",
        "content": "This Privacy Policy applies whenever you:\nregister for MaritimeLink; \nbrowse our website; \nupload certificates; \ncreate your maritime profile; \nuse the Document Wallet; \nbuild your CV; \napply for jobs; \nadvertise vacancies; \nbook training; \nverify your identity; \ncommunicate through Messaging; \nsubscribe to Premium services; \ncontact customer support. \nThis Policy also applies to information collected through:\nemails; \nmobile applications; \ncookies; \nonline forms; \ncustomer support interactions; \nverification processes."
    },
    {
        "number": "6",
        "title": "PRIVACY PRINCIPLES",
        "content": "MaritimeLink processes personal information in accordance with the principles contained within Article 5 UK GDPR.\nWe ensure personal data is:\nLawfully, fairly and transparently processed\nWe explain why information is collected and how it is used.\nCollected for specified purposes\nPersonal information is collected only for legitimate business purposes connected with operating MaritimeLink.\nAdequate and relevant\nWe only request information necessary to provide our services.\nAccurate\nUsers are encouraged to keep their information updated.\nStored only as long as necessary\nRetention periods are defined within this Privacy Policy.\nSecure\nTechnical and organisational safeguards protect personal information against unauthorised access, alteration or loss.\nAccountable\nMaritimeLink maintains records demonstrating compliance with applicable data protection legislation."
    },
    {
        "number": "7",
        "title": "PERSONAL DATA WE COLLECT",
        "content": "Depending on how you use MaritimeLink, we may collect the following categories of information.\n7.1 Identity Information\nFull name \nDate of birth \nNationality \nGender (where voluntarily supplied) \nPassport information \nNational Identity Card information \nDriving licence (where accepted) \nPhotograph \nSelfie images submitted during verification \n\n7.2 Contact Information\nEmail address \nTelephone number \nPostal address \nEmergency contact (where voluntarily supplied) \n7.3 Account Information\nUsername \nPassword (encrypted) \nLogin history \nDevice information \nAuthentication records \nSecurity preferences \n\n7.4 Professional Information\nThe MaritimeLink platform is specifically designed to manage maritime career information.\nAccordingly, users may voluntarily provide:\nCurrent Rank \nPrevious Ranks \nSea Service History \nVessel Types \nEngine Types \nFlag Experience \nCompanies Worked For \nCertificates of Competency \nEndorsements \nSTCW Certificates \nAcademic Qualifications \nProfessional Certifications \nReferees \nSkills \nLanguages \nAvailability Status \nEmployment Preferences \n\n7.5 Document Wallet Information\nWhere users upload professional documents, MaritimeLink may process:\nCertificates \nLicences \nMedical Certificates \nVaccination Records \nTravel Documents \nPassports \nVisas \nSeafarer's Books \nCompany Letters \nSea Service Testimonials \nOther maritime compliance documentation. \nThese documents remain the property of the user.\nMaritimeLink stores them solely for the purposes authorised by the user.\n\n7.6 Identity Verification Data (KYC)\nTo support trust and reduce fraud, MaritimeLink may process:\nGovernment-issued identification \nFacial photographs \nIdentity verification status \nVerification timestamps \nCountry of issue \nDocument expiry dates \nVerification decisions \nManual review notes \nKYC information is processed only for identity verification, fraud prevention and platform security."
    },
    {
        "number": "8",
        "title": "SPECIAL CATEGORY PERSONAL DATA",
        "content": "Certain categories of personal data processed by MaritimeLink may constitute special category personal data under Article 9 of the UK General Data Protection Regulation (\"UK GDPR\"). Such information receives enhanced legal protection due to its sensitive nature.\nDepending on how you use the MaritimeLink platform, we may process special category data including, but not limited to:\nMedical fitness certificates (including ENG1 and equivalent medical certificates); \nVaccination records where uploaded by users; \nInformation contained within medical certificates required for employment; \nBiometric data processed during identity verification where applicable; \nInformation voluntarily disclosed during customer support interactions that relates to health or disability. \nMaritimeLink does not request or process special category data unless it is reasonably necessary for providing our services, complying with legal obligations, preventing fraud, or where you have voluntarily chosen to provide such information.\nWhere possible, users should avoid uploading information that is not required for recruitment, training, professional verification or regulatory compliance.\nAccess to special category data is restricted to authorised personnel with a legitimate business need and is protected using enhanced technical and organisational security measures."
    },
    {
        "number": "9",
        "title": "KNOW YOUR CUSTOMER (KYC) VERIFICATION",
        "content": "MaritimeLink operates a Know Your Customer (\"KYC\") verification programme to improve trust across the platform, reduce fraudulent activity and enhance confidence amongst maritime professionals, recruiters and training providers.\nVerification may include one or more of the following stages:\nEmail verification; \nTelephone verification using one-time passcodes (OTP); \nGovernment-issued identity document verification; \nFacial image comparison; \nManual identity review by authorised MaritimeLink personnel; \nVerification of supporting documentation where necessary. \nThe KYC process enables MaritimeLink to:\nverify the identity of users; \nreduce impersonation; \nminimise fraudulent recruitment activities; \nmaintain platform integrity; \nimprove recruiter confidence; \nsatisfy legal and regulatory obligations where applicable. \nCompletion of KYC verification may be required before users can access certain features of the platform, including:\napplying for vacancies; \nsharing professional documents; \nobtaining the Verified Professional Badge; \nadvertising vacancies; \npublishing training courses; \nsubscribing to certain premium services. \nSubmission of KYC information does not guarantee approval.\nMaritimeLink reserves the right to request additional documentation where information is incomplete, inconsistent or requires further verification.\nWhere verification cannot reasonably be completed, access to certain platform services may be restricted or refused."
    },
    {
        "number": "10",
        "title": "OCR AND AI-ASSISTED DOCUMENT PROCESSING",
        "content": "To improve efficiency, reduce manual processing and enhance user experience, MaritimeLink uses Optical Character Recognition (\"OCR\") technology together with AI-assisted validation tools when users upload documents.\nOCR technology enables MaritimeLink to extract information from uploaded documents, including but not limited to:\ncertificate titles; \ncertificate numbers; \nissuing authorities; \ndates of issue; \nexpiry dates; \nnames; \nreference numbers; \ndocument classifications. \nAI-assisted processing may be used to:\nidentify incomplete uploads; \ndetect duplicate documents; \nidentify potential alterations; \nhighlight inconsistencies between uploaded documents; \nidentify potential fraud indicators; \nimprove document quality; \nsupport expiry monitoring. \nAI technologies assist MaritimeLink personnel and are not solely relied upon when making significant decisions affecting users.\nWhere automated systems identify anomalies, documents may be referred for manual review by authorised MaritimeLink administrators.\nUsers may request human intervention where they believe automated processing has produced an inaccurate outcome.\nMaritimeLink continuously reviews automated processing systems to minimise bias, improve accuracy and ensure compliance with applicable data protection legislation."
    },
    {
        "number": "11",
        "title": "VERIFIED PROFESSIONAL BADGE",
        "content": "The MaritimeLink Verified Professional Badge is intended to provide recruiters and other users with increased confidence regarding the identity and verification status of maritime professionals.\nThe badge may be awarded following successful completion of MaritimeLink's verification procedures, which may include:\nidentity verification; \nKYC approval; \ndocument validation; \nverification of professional qualifications; \nsuccessful administrative review. \nThe badge does not represent:\nemployment endorsement; \ncompetency certification; \nprofessional licensing; \nguarantee of employment suitability; \nconfirmation of current legal eligibility to work in any particular jurisdiction. \nThe badge simply indicates that MaritimeLink has successfully completed its verification procedures based upon the information available at the time of assessment.\nMaritimeLink reserves the right to suspend, remove or revoke the Verified Professional Badge where:\nverification information becomes inaccurate; \nsupporting documents expire; \nfraudulent information is identified; \nusers fail to respond to verification requests; \nplatform policies are breached. \nBadge status may be periodically reviewed to maintain the integrity of the MaritimeLink verification programme."
    },
    {
        "number": "12",
        "title": "HOW WE USE YOUR PERSONAL INFORMATION",
        "content": "MaritimeLink processes personal information for a variety of legitimate business purposes connected with operating and improving the platform.\nDepending upon how you use MaritimeLink, your information may be used to:\nAccount Administration\ncreate user accounts; \nauthenticate users; \nmaintain platform security; \nmanage account settings; \nrecover accounts. \nIdentity Verification\nverify user identities; \nconduct KYC reviews; \nprevent impersonation; \nreduce fraud. \nProfessional Profiles\ncreate professional profiles; \ngenerate maritime CVs; \ndisplay qualifications; \npresent employment history; \nimprove recruiter matching. \nDocument Wallet\nsecurely store professional documentation; \norganise uploaded certificates; \nprovide expiry reminders; \nfacilitate secure sharing. \nRecruitment Services\nenable job applications; \nconnect professionals with recruiters; \nimprove candidate matching; \nmaintain application histories. \nTraining Marketplace\nfacilitate course bookings; \nverify eligibility for courses; \ncommunicate with training providers; \nmanage bookings. \nPlatform Communications\ndeliver service notifications; \nsend verification updates; \nprovide customer support; \nrespond to enquiries. \nSecurity\ninvestigate suspicious activity; \ndetect fraud; \nenforce platform policies; \nmaintain system integrity. \nPlatform Improvement\nanalyse usage patterns; \nimprove functionality; \ndevelop new features; \nmonitor service performance. \nMaritimeLink will only process personal information where an appropriate lawful basis exists under applicable data protection legislation."
    },
    {
        "number": "13",
        "title": "LEGAL BASES FOR PROCESSING (ARTICLE 6 UK GDPR)",
        "content": "Under Article 6 of the UK GDPR, MaritimeLink relies upon one or more lawful bases when processing personal data.\nPerformance of a Contract — Article 6(1)(b)\nWe process personal data where necessary to provide services requested by users, including:\naccount creation; \nprofile management; \njob applications; \nsubscription services; \nmessaging; \ndocument storage. \nLegal Obligation — Article 6(1)(c)\nWe may process personal information where necessary to comply with legal obligations, including obligations relating to fraud prevention, financial reporting, regulatory compliance and lawful requests from competent authorities.\nLegitimate Interests — Article 6(1)(f)\nMaritimeLink has legitimate interests in:\noperating a secure platform; \npreventing fraud; \nimproving user experience; \nmaintaining service quality; \nprotecting platform users; \ndeveloping new features; \nmaintaining business records. \nWhere processing relies upon legitimate interests, MaritimeLink carefully balances those interests against the rights and freedoms of affected individuals.\nConsent — Article 6(1)(a)\nCertain activities are carried out only where users have provided consent, including:\nmarketing communications; \noptional cookies; \ncertain optional platform features. \nUsers may withdraw consent at any time without affecting the lawfulness of processing carried out before withdrawal."
    },
    {
        "number": "14",
        "title": "PROCESSING OF SPECIAL CATEGORY DATA (ARTICLE 9 UK GDPR)",
        "content": "Where MaritimeLink processes special category personal data, we rely upon one or more of the lawful conditions set out in Article 9 UK GDPR.\nDepending upon the circumstances, processing may be carried out because:\nyou have provided explicit consent; \nprocessing is necessary for employment or social protection obligations; \nprocessing is necessary for reasons of substantial public interest, including fraud prevention; \nprocessing is necessary for the establishment, exercise or defence of legal claims; \nprocessing is manifestly made public by the individual; \nanother condition permitted under UK data protection legislation applies. \nSpecial category information is never processed for marketing purposes.\nMaritimeLink applies additional safeguards to protect sensitive information, including restricted access controls, encryption, audit logging, role-based permissions and enhanced security monitoring."
    },
    {
        "number": "15",
        "title": "DOCUMENT WALLET",
        "content": "The MaritimeLink Document Wallet is a secure digital storage facility that enables Professionals to upload, organise, manage and securely access maritime documents from a single location.\nThe Document Wallet is intended to simplify professional document management throughout a seafarer's career and reduce the repeated submission of documentation during recruitment and training processes.\nDepending upon the user's profession and requirements, the Document Wallet may contain:\nCertificates of Competency; \nSTCW Certificates; \nFlag State Endorsements; \nMedical Certificates (including ENG1 or equivalent); \nSeafarer's Books; \nPassports; \nVisas; \nAcademic Qualifications; \nProfessional Licences; \nSea Service Testimonials; \nEmployment References; \nVaccination Certificates; \nTravel Documentation; \nCompany Letters; \nOther professional maritime documentation voluntarily uploaded by the user. \nUsers retain ownership of all uploaded documents.\nMaritimeLink does not acquire ownership rights over any document uploaded to the Document Wallet.\nUsers remain solely responsible for ensuring that uploaded documentation:\nis accurate; \nis complete; \nbelongs to them; \nis lawfully uploaded; \nremains current; \nis not misleading or fraudulent. \nMaritimeLink may use uploaded documents solely for the purposes described within this Privacy Policy, including identity verification, document validation, recruitment facilitation, secure sharing, expiry monitoring and customer support.\nUploaded documents are encrypted during transmission and whilst stored using industry-standard security measures."
    },
    {
        "number": "16",
        "title": "SECURE DOCUMENT SHARING",
        "content": "MaritimeLink allows users to securely share selected documents stored within their Document Wallet with authorised third parties.\nSecure document sharing enables users to:\nshare professional certificates with recruiters; \nprovide documentation to training providers; \nsubmit qualifications during recruitment; \ndemonstrate compliance with employer requirements; \nreduce repeated uploads across multiple applications. \nUsers remain in control of documents shared through the platform.\nWhere available, users may control:\nwhich documents are shared; \nthe recipient; \nduration of access; \npermission settings; \nwithdrawal of access. \nRecipients receiving shared documentation are contractually required to process such information in accordance with applicable data protection legislation and their own privacy obligations.\nMaritimeLink is not responsible for the subsequent use of documents by third parties once users have intentionally chosen to share them, except where required by applicable law.\nUsers should carefully consider the information they choose to share."
    },
    {
        "number": "17",
        "title": "CV BUILDER",
        "content": "The MaritimeLink CV Builder enables Professionals to generate structured maritime curriculum vitae using information stored within their profile.\nInformation may include:\npersonal details; \nprofessional summary; \nCertificates of Competency; \nendorsements; \nsea service history; \nvessel experience; \nengine experience; \nqualifications; \nSTCW certification; \nmedical certification; \nprofessional skills; \nemployment history; \nreferees; \navailability status. \nThe CV Builder automatically formats this information into a professional maritime CV.\nUsers remain responsible for reviewing generated CVs before submitting them to employers.\nMaritimeLink does not verify every statement contained within a generated CV unless specifically indicated through platform verification services.\nUsers may edit or remove profile information at any time.\nDeleting profile information may affect the appearance of generated CVs."
    },
    {
        "number": "18",
        "title": "PROFESSIONAL PROFILES",
        "content": "Every registered Professional may create a public or partially visible MaritimeLink professional profile.\nProfessional profiles are designed to increase visibility within the maritime recruitment industry while allowing users to maintain appropriate control over their information.\nDepending upon individual privacy settings, profile information may include:\nname; \nprofessional photograph; \nrank; \nnationality; \nsea service experience; \nqualifications; \ncertifications; \nendorsements; \navailability status; \nprofessional summary; \nskills; \nlanguages; \nVerified Professional Badge; \nselected documents where authorised by the user. \nUsers may modify profile visibility through their account settings.\nCertain profile information may remain visible where necessary for platform functionality, fraud prevention or legal compliance."
    },
    {
        "number": "19",
        "title": "RECRUITER PORTAL",
        "content": "The MaritimeLink Recruiter Portal enables authorised recruitment organisations to identify, evaluate and communicate with suitable maritime professionals.\nRecruiters may access personal information only where:\nusers have chosen to make information available; \nusers submit applications; \nusers respond to recruiter enquiries; \ndisclosure is otherwise permitted by platform functionality. \nRecruiters may view information including:\nprofessional profiles; \nqualifications; \nsea service experience; \nCVs; \nselected shared documentation; \navailability status; \nmessaging history relevant to recruitment. \nRecruiters are independent data controllers in respect of personal information they collect through MaritimeLink.\nOnce information has been shared with a recruiter, the recruiter becomes independently responsible for complying with applicable data protection legislation.\nMaritimeLink is not responsible for recruitment decisions made by third-party employers."
    },
    {
        "number": "20",
        "title": "TRAINING MARKETPLACE",
        "content": "The MaritimeLink Training Marketplace enables maritime training providers to advertise professional courses and enables users to discover, enquire about and book training opportunities.\nWhen using the Training Marketplace, MaritimeLink may process:\nbooking information; \ncourse enquiries; \nattendance records; \npayment confirmations; \ntraining preferences; \ncommunications between users and providers. \nWhere users proceed with external training providers, additional information may be shared where necessary to complete bookings.\nTraining providers are responsible for processing personal information in accordance with their own privacy policies.\nMaritimeLink encourages users to review the privacy policies of individual training providers before submitting personal information."
    },
    {
        "number": "21",
        "title": "MESSAGING AND COMMUNICATIONS",
        "content": "MaritimeLink provides an internal messaging service enabling communication between:\nProfessionals; \nRecruiters; \nTraining Providers; \nMaritimeLink Support. \nMessages may include:\nrecruitment discussions; \ninterview invitations; \ntraining enquiries; \ncustomer support; \ndocument requests; \nbooking communications. \nMessages transmitted through the platform are protected using encrypted communication channels where technically feasible.\nMaritimeLink does not routinely monitor private conversations.\nHowever, we reserve the right to review communications where reasonably necessary to:\ninvestigate fraud; \ninvestigate abuse; \nrespond to legal requests; \nenforce platform policies; \ninvestigate security incidents; \nprotect users. \nSuch reviews are carried out only by authorised personnel and only where reasonably necessary."
    },
    {
        "number": "22",
        "title": "NOTIFICATIONS",
        "content": "MaritimeLink sends notifications to assist users in managing their professional activities.\nNotifications may include:\nService Notifications\naccount verification; \nlogin alerts; \npassword changes; \nsecurity notifications; \nKYC updates; \nsubscription information. \nRecruitment Notifications\nnew job opportunities; \napplication updates; \nrecruiter messages; \ninterview invitations. \nTraining Notifications\nbooking confirmations; \ncourse reminders; \nprovider updates. \nCompliance Notifications\ndocument expiry reminders; \nverification status; \nbadge updates; \ncompliance alerts. \nNotifications may be delivered through:\nemail; \nin-app notifications; \nSMS (where enabled); \nmobile push notifications. \nUsers may manage notification preferences through their account settings.\nCertain notifications relating to security, account integrity, legal obligations and essential platform functionality cannot be disabled."
    },
    {
        "number": "23",
        "title": "USER GENERATED CONTENT",
        "content": "Users may voluntarily submit content to MaritimeLink including profile information, professional summaries, employment history, skills, comments, reviews, messages, uploaded documents and other information.\nUsers are solely responsible for ensuring that content they submit:\nis accurate; \nis lawful; \ndoes not infringe third-party rights; \ndoes not contain malicious software; \ncomplies with MaritimeLink's Terms and Conditions and Acceptable Use Policy. \nMaritimeLink reserves the right to remove or restrict access to user-generated content where it reasonably believes such content:\nis fraudulent; \nis misleading; \ninfringes intellectual property rights; \nbreaches applicable law; \nposes a security risk; \nviolates platform policies. \nRemoval of content does not necessarily result in account suspension or termination, although repeated or serious breaches may lead to enforcement action in accordance with our Terms and Conditions."
    },
    {
        "number": "24",
        "title": "SUBSCRIPTIONS, PAYMENTS AND STRIPE PROCESSING",
        "content": "MaritimeLink offers both free and subscription-based services. Subscription services may be available to Professionals, Recruiters, Training Providers and other authorised users depending upon the features offered at the time.\nPayments made through MaritimeLink are processed using Stripe, our third-party payment service provider.\nMaritimeLink does not store or retain full payment card details.\nWhen you purchase a subscription or other paid service, we may process or receive information including:\nSubscriber name; \nBilling address; \nEmail address; \nSubscription plan; \nPayment status; \nTransaction reference numbers; \nInvoice information; \nVAT information where applicable; \nSubscription renewal dates; \nPayment history. \nSensitive payment information, including full debit or credit card numbers, security codes (CVV/CVC), or complete payment credentials, is collected and processed directly by Stripe using secure encrypted payment infrastructure.\nMaritimeLink receives confirmation only of whether a payment has been authorised, declined, refunded or otherwise processed.\nPayment processing is carried out in accordance with Stripe's own Privacy Policy and applicable financial regulations.\nWhere subscriptions automatically renew, users will receive advance notice where required by applicable law and may manage or cancel subscriptions through their account settings, subject to the applicable Subscription Terms and Conditions."
    },
    {
        "number": "25",
        "title": "COOKIES AND SIMILAR TECHNOLOGIES",
        "content": "MaritimeLink uses cookies and similar technologies to improve the functionality, security and performance of our website and applications.\nCookies are small text files placed on your device that allow websites and applications to recognise your browser or device during future visits.\nWe use cookies for a number of legitimate purposes, including:\nmaintaining secure login sessions; \nremembering user preferences; \nimproving website performance; \nanalysing platform usage; \nenhancing security; \npreventing fraudulent activity; \nmeasuring the effectiveness of marketing campaigns; \nimproving user experience. \nMaritimeLink categorises cookies as follows:\nStrictly Necessary Cookies\nThese cookies are essential for the operation of the platform and cannot be disabled. They enable core functionality such as authentication, security, session management and fraud prevention.\nFunctional Cookies\nThese cookies remember user preferences, language settings and other choices to provide a more personalised experience.\nAnalytics Cookies\nAnalytics cookies help us understand how visitors use MaritimeLink so that we can improve our services, identify usability issues and monitor platform performance.\nPerformance Cookies\nPerformance cookies allow us to measure response times, system stability and technical performance to improve reliability.\nMarketing Cookies\nWhere applicable and subject to user consent, marketing cookies may be used to measure advertising effectiveness and deliver relevant promotional content.\nNon-essential cookies are used only after obtaining valid consent where required under the Privacy and Electronic Communications Regulations 2003 (\"PECR\").\nUsers may withdraw cookie consent or modify their preferences at any time through the Cookie Preference Centre available on our website.\nFurther information is available in the MaritimeLink Cookie Policy."
    },
    {
        "number": "26",
        "title": "ANALYTICS AND PLATFORM IMPROVEMENT",
        "content": "MaritimeLink continually monitors the performance, security and usability of the platform to improve user experience and maintain service quality.\nWe may collect information relating to:\nbrowser type; \noperating system; \ndevice type; \nIP address; \napproximate geographic location; \npages visited; \ntime spent using services; \nsearch activity; \nfeature usage; \nerror reports; \napplication crashes; \nreferral sources; \ninteraction with platform features. \nAnalytics information is generally aggregated wherever reasonably possible and is not intended to identify individual users unless required for security, fraud prevention or technical troubleshooting.\nWe use analytics information to:\nimprove platform performance; \nidentify technical issues; \nunderstand user behaviour; \nprioritise product improvements; \nmeasure feature adoption; \nenhance accessibility; \nimprove recruitment matching; \nimprove document processing workflows; \nenhance platform security. \nWhere third-party analytics providers are used, MaritimeLink takes reasonable steps to ensure they process information in accordance with applicable data protection legislation."
    },
    {
        "number": "27",
        "title": "THIRD-PARTY SERVICE PROVIDERS",
        "content": "MaritimeLink relies upon carefully selected third-party service providers to operate certain aspects of the platform.\nDepending upon the services used, these providers may process personal information on MaritimeLink's behalf.\nExamples include providers responsible for:\ncloud hosting; \nsecure data storage; \npayment processing; \nidentity verification; \nemail delivery; \nSMS delivery; \npush notifications; \nanalytics; \ncustomer support; \ninfrastructure monitoring; \ndocument processing; \ncybersecurity. \nAll third-party processors are required to:\nprocess information only on documented instructions from MaritimeLink; \nimplement appropriate technical and organisational security measures; \nmaintain confidentiality; \ncomply with applicable data protection legislation; \nnotify MaritimeLink of relevant security incidents where required. \nWhere appropriate, MaritimeLink enters into Data Processing Agreements with third-party processors to ensure compliance with Article 28 UK GDPR."
    },
    {
        "number": "28",
        "title": "INTERNATIONAL DATA TRANSFERS",
        "content": "MaritimeLink primarily stores and processes personal information within the United Kingdom and, where appropriate, the European Economic Area (\"EEA\").\nHowever, certain trusted service providers may process personal information outside the United Kingdom.\nWhere international transfers occur, MaritimeLink ensures that appropriate safeguards are implemented, including one or more of the following:\nUK International Data Transfer Agreement (IDTA); \nUK Addendum to the European Commission Standard Contractual Clauses; \nAdequacy Regulations recognised by the UK Government; \nanother lawful transfer mechanism permitted under applicable legislation. \nWhere reasonably necessary, MaritimeLink also conducts transfer risk assessments to ensure that transferred personal information continues to receive an appropriate level of protection."
    },
    {
        "number": "29",
        "title": "INFORMATION SECURITY",
        "content": "MaritimeLink takes the security of personal information extremely seriously.\nWe implement appropriate technical and organisational measures designed to protect information against accidental loss, unauthorised access, disclosure, alteration or destruction.\nSecurity measures may include:\nencryption during transmission; \nencryption of stored information where appropriate; \nsecure cloud infrastructure; \nrole-based access controls; \nmulti-factor authentication for administrative accounts; \nleast-privilege access principles; \ncontinuous security monitoring; \naudit logging; \nvulnerability management; \npenetration testing; \nmalware protection; \nfirewall protection; \nintrusion detection; \nbackup procedures; \ndisaster recovery planning; \nstaff confidentiality obligations. \nAccess to sensitive information is restricted to authorised personnel who require such access to perform their duties.\nDespite these measures, no online platform can guarantee absolute security.\nUsers also play an important role in protecting their accounts and should maintain strong passwords, enable available security features and immediately report any suspected unauthorised access."
    },
    {
        "number": "30",
        "title": "DATA RETENTION",
        "content": "MaritimeLink retains personal information only for as long as reasonably necessary to fulfil the purposes described within this Privacy Policy, comply with legal obligations, resolve disputes and enforce our agreements.\nRetention periods vary depending upon the category of information and applicable legal requirements.\nExamples include:\nData Category\nTypical Retention Period\nAccount Information\nDuration of account plus up to 6 years following closure where legally required\nIdentity Verification Records\nUp to 6 years after verification or account closure where required for fraud prevention or legal compliance\nProfessional Profiles\nUntil deleted by the user or account closure, subject to legal retention requirements\nDocument Wallet Files\nUntil deleted by the user or account closure unless longer retention is required by law\nSubscription and Billing Records\nUp to 6 years for accounting and tax purposes\nCustomer Support Records\nUp to 3 years after resolution\nSystem Security Logs\nTypically between 12 and 24 months unless longer retention is required for security investigations\nAnalytics Data\nAggregated or anonymised where reasonably practicable\n\nWhere retention periods expire, MaritimeLink securely deletes, anonymises or irreversibly destroys personal information unless continued retention is required by law or for the establishment, exercise or defence of legal claims."
    },
    {
        "number": "31",
        "title": "BUSINESS CONTINUITY AND DISASTER RECOVERY",
        "content": "To ensure the continued availability and integrity of the MaritimeLink platform, we maintain business continuity and disaster recovery procedures.\nThese procedures are designed to:\nminimise service disruption; \nprotect personal information during system failures; \nmaintain backup copies of critical systems; \nsupport timely restoration of services following security incidents or technical failures; \nensure continued compliance with applicable legal obligations. \nBackup systems are protected using appropriate security controls and are retained only for legitimate operational purposes.\nWhere backup copies contain personal information, they are subject to the same security and confidentiality obligations as live production systems."
    },
    {
        "number": "32",
        "title": "YOUR RIGHTS UNDER UK GDPR",
        "content": "Under the UK General Data Protection Regulation and the Data Protection Act 2018, you have a number of legal rights regarding the personal information MaritimeLink holds about you.\nThese rights are not absolute and may be subject to certain legal exemptions or restrictions. Where an exemption applies, MaritimeLink will explain the reasons for any refusal where we are legally permitted to do so.\nSubject to applicable law, you have the right to:\nRight of Access\nRequest confirmation as to whether MaritimeLink processes your personal data and obtain a copy of the personal information we hold about you together with supplementary information explaining how it is processed.\nRight to Rectification\nRequest correction of inaccurate or incomplete personal information. Users are encouraged to keep their profiles and uploaded documentation up to date through their account settings.\nRight to Erasure (\"Right to be Forgotten\")\nRequest deletion of your personal information where:\nthe information is no longer necessary for the purposes for which it was collected; \nyou withdraw consent and there is no other lawful basis for processing; \nthe processing is unlawful; \nyou successfully object to processing based on legitimate interests; or \nMaritimeLink is legally required to erase the information. \nThis right is subject to legal obligations requiring MaritimeLink to retain certain records.\nRight to Restrict Processing\nRequest that MaritimeLink temporarily restrict the processing of your personal information where:\nthe accuracy of the information is disputed; \nthe processing is unlawful but you oppose deletion; \nthe information is required for legal claims; or \nyou have objected to processing pending verification. \nRight to Data Portability\nWhere processing is based upon consent or contract and carried out by automated means, you may request a copy of your personal information in a structured, commonly used and machine-readable format.\nRight to Object\nYou may object to processing based upon MaritimeLink's legitimate interests where your individual circumstances justify such objection.\nMaritimeLink will cease such processing unless compelling legitimate grounds exist which override your interests, rights and freedoms or the processing is necessary for legal claims.\nRights Relating to Direct Marketing\nYou have the absolute right to object to the processing of your personal information for direct marketing purposes.\nWhere you exercise this right, MaritimeLink will cease marketing communications without undue delay.\nRights Relating to Automated Decision-Making\nWhere applicable, you have the right to request human intervention, express your point of view and challenge decisions based solely upon automated processing where such decisions produce legal or similarly significant effects."
    },
    {
        "number": "33",
        "title": "HOW TO EXERCISE YOUR RIGHTS",
        "content": "Requests relating to your personal information may be submitted by contacting MaritimeLink using the details provided in this Privacy Policy.\nTo protect your information and prevent unauthorised disclosure, MaritimeLink may request reasonable evidence of identity before responding to your request.\nWhere legally required, MaritimeLink will normally respond within one calendar month of receiving a valid request.\nWhere requests are particularly complex or numerous, this period may be extended in accordance with applicable legislation. Where an extension is necessary, you will be informed of the reasons and expected response timeframe.\nMaritimeLink will generally not charge a fee for responding to requests unless they are manifestly unfounded, excessive or repetitive, in which case we reserve the right to charge a reasonable administrative fee or refuse the request where permitted by law."
    },
    {
        "number": "34",
        "title": "MARKETING COMMUNICATIONS",
        "content": "MaritimeLink may send marketing communications relating to platform features, recruitment opportunities, training services, product updates, newsletters and promotional campaigns where permitted by law.\nMarketing communications will be sent only where:\nyou have provided your consent; \nyou have not opted out where soft opt-in rules apply under PECR; or \nanother lawful basis exists. \nYou may withdraw consent or unsubscribe from marketing communications at any time by:\nselecting the unsubscribe link contained within marketing emails; \nupdating your account preferences; \ncontacting MaritimeLink directly. \nWithdrawal of marketing consent does not affect service-related communications necessary for the operation of your account."
    },
    {
        "number": "35",
        "title": "AUTOMATED DECISION-MAKING AND PROFILING",
        "content": "MaritimeLink uses certain automated technologies to improve efficiency, reduce fraud and enhance platform functionality.\nExamples include:\nOCR extraction of document information; \nfraud detection indicators; \nduplicate document detection; \ndocument quality assessment; \nrecruiter matching algorithms; \nexpiry reminder generation; \nnotification preferences. \nThese automated processes are intended to support, rather than replace, human decision-making.\nWhere a decision producing legal or similarly significant effects is based solely on automated processing, MaritimeLink will implement appropriate safeguards required under Article 22 UK GDPR, including the right to request human review where applicable."
    },
    {
        "number": "36",
        "title": "CHILDREN'S PRIVACY",
        "content": "MaritimeLink is intended exclusively for individuals seeking employment, recruitment or professional development within the maritime industry.\nThe platform is not designed for children.\nUsers must be at least eighteen (18) years of age, or such higher minimum age as may be required under applicable employment legislation within their jurisdiction, to create an account.\nMaritimeLink does not knowingly collect personal information from children.\nWhere MaritimeLink becomes aware that personal information belonging to a child has been collected without appropriate legal authority, reasonable steps will be taken to delete that information without undue delay."
    },
    {
        "number": "37",
        "title": "PERSONAL DATA BREACHES",
        "content": "MaritimeLink maintains documented procedures for identifying, investigating and responding to personal data breaches.\nWhere a personal data breach is likely to result in a risk to the rights and freedoms of individuals, MaritimeLink will notify the Information Commissioner's Office (ICO) without undue delay and, where feasible, within seventy-two (72) hours of becoming aware of the breach, in accordance with Article 33 UK GDPR.\nWhere a breach is likely to result in a high risk to affected individuals, MaritimeLink will also notify affected users without undue delay unless an exemption under applicable legislation applies.\nMaritimeLink continuously reviews security incidents to strengthen its technical and organisational safeguards and reduce the likelihood of future incidents."
    },
    {
        "number": "38",
        "title": "COMPLAINTS",
        "content": "MaritimeLink is committed to resolving privacy concerns fairly, promptly and transparently.\nIf you have any concerns regarding the way your personal information has been handled, you should contact MaritimeLink in the first instance using the contact details provided below.\nWe will investigate your complaint and endeavour to provide a substantive response as soon as reasonably practicable.\nIf you remain dissatisfied, you have the right to lodge a complaint with the Information Commissioner's Office (ICO), the United Kingdom's independent supervisory authority for data protection matters.\nInformation Commissioner’s Office\nWycliffe House\nWater Lane\nWilmslow\nCheshire\nSK9 5AF\nUnited Kingdom\nWebsite: https://ico.org.uk\nTelephone: 0303 123 1113\nNothing in this Privacy Policy limits your statutory rights to seek judicial remedies or lodge complaints with competent supervisory authorities where permitted by law."
    },
    {
        "number": "39",
        "title": "ACCOUNT CLOSURE AND DELETION",
        "content": "Users may request closure of their MaritimeLink account at any time through their account settings or by contacting MaritimeLink.\nUpon closure of an account:\naccess to the platform will cease; \npublic profile visibility will be removed; \nactive subscriptions will be cancelled in accordance with the applicable Subscription Terms; \npersonal information will be scheduled for deletion or anonymisation in accordance with our retention policy. \nCertain information may continue to be retained following account closure where necessary:\nto comply with legal obligations; \nfor accounting or taxation purposes; \nto investigate fraud; \nto resolve disputes; \nto enforce contractual rights; \nfor the establishment, exercise or defence of legal claims. \nBackup copies containing personal information will be securely overwritten or deleted in accordance with MaritimeLink's backup retention procedures."
    },
    {
        "number": "40",
        "title": "CHANGES TO THIS PRIVACY POLICY",
        "content": "MaritimeLink may amend this Privacy Policy from time to time to reflect:\nchanges in applicable legislation; \nnew platform features; \ntechnological developments; \nsecurity improvements; \nchanges to processing activities; \nbusiness developments. \nWhere changes are material, MaritimeLink will take reasonable steps to notify users through appropriate channels, including:\nemail notifications; \nin-app notifications; \nwebsite notices; or \naccount announcements. \nThe \"Last Updated\" date displayed at the beginning of this Privacy Policy indicates the date on which the latest version became effective.\nContinued use of MaritimeLink following publication of an updated Privacy Policy constitutes acknowledgement of the revised Policy."
    },
    {
        "number": "41",
        "title": "CONTACTING MARITIMELINK",
        "content": "Questions, requests or concerns relating to this Privacy Policy or the processing of personal information should be directed to:\nCompliance Team\nMaritimeLink Ltd\nUnited Kingdom\nEmail: compliance@maritimelink.co \nWebsite: www.maritimelink.co \nWhere appropriate, correspondence may be directed to MaritimeLink's Data Protection Lead using the contact details above."
    },
    {
        "number": "42",
        "title": "GOVERNING LAW",
        "content": "This Privacy Policy shall be governed by and construed in accordance with the laws of England and Wales.\nAny dispute arising out of or in connection with this Privacy Policy shall be subject to the exclusive jurisdiction of the courts of England and Wales, except where mandatory consumer protection legislation provides otherwise."
    },
    {
        "number": "43",
        "title": "FINAL PROVISIONS",
        "content": "This Privacy Policy forms an integral part of MaritimeLink's legal framework and should be read together with our:\nTerms and Conditions; \nCookie Policy; \nAcceptable Use Policy; \nSubscription Terms; \nRecruiter Terms; \nTraining Provider Terms; \nData Processing Agreement (where applicable); and \nany additional legal notices published by MaritimeLink from time to time. \nIf any provision of this Privacy Policy is found to be invalid or unenforceable, the remaining provisions shall remain in full force and effect."
    }
];
